Repository prusa3d/Prusa-Firmware, pull requests merged in 2020-01, with the labels that each got.

#2395 Improve raise_z_above to always raise when at Z_MIN
  Firmware/Marlin_main.cpp
Labels: FW 3.9.x

#2381 Remove "relative_mode", only use "axis_relative_modes"
  Firmware/Marlin_main.cpp
Labels: FW 3.9.x

#2382 Fix lcd "Stop" when used within a pause
  Firmware/Marlin.h
  Firmware/Marlin_main.cpp
  Firmware/ultralcd.cpp
Labels: FW 3.9.x

#2402 Do not show sheet on status screen if less than 2 are initialized
  Firmware/ultralcd.cpp
Labels: FW 3.9.x

#2403 Show ? near Z value if the position is unknown
  Firmware/ultralcd.cpp
Labels: FW 3.9.x

#1909 Linear Advance 1.5 Returns
  Firmware/ConfigurationStore.cpp
  Firmware/Configuration_adv.h
  Firmware/Marlin_main.cpp
  Firmware/eeprom.h
  Firmware/fsensor.cpp
  Firmware/fsensor.h
  Firmware/la10compat.cpp
  Firmware/la10compat.h
  Firmware/menu.cpp
  Firmware/menu.h
  Firmware/messages.c
  Firmware/messages.h
  Firmware/planner.cpp
  Firmware/planner.h
  Firmware/speed_lookuptable.cpp
  Firmware/speed_lookuptable.h
  Firmware/stepper.cpp
  Firmware/stepper.h
  Firmware/ultralcd.cpp
Labels: FW 3.9.x

#2404 New lcd_print_stop function
  Firmware/Marlin_main.cpp
  Firmware/ultralcd.cpp
Labels: FW 3.9.x

#1933 Enable MMU cutter.
  Firmware/mmu.cpp
  Firmware/variants/1_75mm_MK25-RAMBo10a-E3Dv6full.h
  Firmware/variants/1_75mm_MK25-RAMBo13a-E3Dv6full.h
  Firmware/variants/1_75mm_MK25S-RAMBo10a-E3Dv6full.h
  Firmware/variants/1_75mm_MK25S-RAMBo13a-E3Dv6full.h
  Firmware/variants/1_75mm_MK3-EINSy10a-E3Dv6full.h
  Firmware/variants/1_75mm_MK3S-EINSy10a-E3Dv6full.h
Labels: FW 3.9.x

#2368 Unretract when resuming a paused print
  Firmware/Marlin.h
  Firmware/Marlin_main.cpp
  Firmware/ultralcd.cpp
Labels: FW 3.9.0 Beta

#2383 Fix fan_check_error check in usb print resume
  Firmware/ultralcd.cpp
Labels: FW 3.9.0 Beta

#2393 Sync before resume
  Firmware/Marlin_main.cpp
  Firmware/mmu.cpp
  Firmware/ultralcd.cpp
Labels: FW 3.9.0 Beta

#2416 Fix incorrect usage of plan_set_e_position() in G92 E*
  Firmware/Marlin_main.cpp
  Firmware/planner.cpp
  Firmware/planner.h
  Firmware/stepper.cpp
Labels: FW 3.9.0 Beta

#2354 Gcode doxygen documentation
  Firmware/Dcodes.cpp
  Firmware/Marlin_main.cpp
Labels: FW 3.9.0 Beta

#2437 Accurate PowerPanic E/Z recovery
  Firmware/Marlin.h
  Firmware/Marlin_main.cpp
  Firmware/eeprom.h
  Firmware/planner.cpp
  Firmware/variants/1_75mm_MK3-EINSy10a-E3Dv6full.h
  Firmware/variants/1_75mm_MK3S-EINSy10a-E3Dv6full.h
Labels: FW 3.9.0 RC

#2307 Save/restore hotend temperatures above 255C in powerpanic
  Firmware/Marlin_main.cpp
  Firmware/eeprom.h
Labels: FW 3.9.0 RC

#2438 Really poweroff Z motors when PSU_Delta is defined
  Firmware/Marlin.h
  Firmware/Marlin_main.cpp
Labels: FW 3.9.0 RC

#2443 Setup the UVLO interrupt later during initialization
  Firmware/Marlin_main.cpp
Labels: FW 3.9.0 RC

#2446 Refuse to start a print if power is lost before arming uvlo
  Firmware/Marlin_main.cpp
  Firmware/messages.c
  Firmware/messages.h
Labels: FW 3.9.0 RC

#2394 Avoid more recursive behavior in fsensor_update
  Firmware/Marlin_main.cpp
  Firmware/fsensor.cpp
Labels: FW 3.9.0 RC

#2436 Do not clear axis known position when Z is set to silent
  Firmware/Marlin_main.cpp
Labels: FW 3.9.0 RC

#2431 selfTest workflow optimalization
  Firmware/ultralcd.cpp
Labels: FW 3.9.0 RC
