Repository prusa3d/Prusa-Firmware, pull requests merged in 2023-10, with the labels that each got.

#4420 PFW-1543 Save print type in EEPROM
  Firmware/Marlin.h
  Firmware/Marlin_main.cpp
  Firmware/cardreader.cpp
  Firmware/eeprom.h
  Firmware/power_panic.cpp
  Firmware/power_panic.h
Labels: powerpanic, Prusa-Link_Connect

#4439 Add `’` and `Ê` to charset
  lang/lib/charset.py
Labels: translations

#4442 Update Italian
  lang/po/Firmware_it.po
Labels: translations

#4411 Polish translation update.
  lang/po/Firmware_pl.po
Labels: translations

#4396 PFW-1538: Add M420
  Firmware/Marlin_main.cpp
Labels: Prusa-Link_Connect

#4440 Update Spanish diacritics
  lang/po/Firmware_es.po
Labels: translations

#4441 PFW-1445: Update and shorten French
  lang/po/Firmware_fr.po
Labels: translations

#4454 MMU: Backport code changes from 32-bit firmware
  Firmware/mmu2.cpp
  Firmware/mmu2.h
  Firmware/mmu2_error_converter.cpp
  Firmware/mmu2_power.cpp
  Firmware/mmu2_protocol_logic.cpp
  Firmware/mmu2_protocol_logic.h
  Firmware/mmu2_reporting.cpp
  Firmware/mmu2_reporting.h
Labels: in progress, MMU

#4460 PFW-1523 Add a new timer for Prusa Link
  CMakeLists.txt
  Firmware/Configuration_adv.h
  Firmware/Marlin_main.cpp
  Firmware/host.cpp
  Firmware/host.h
Labels: Prusa-Link_Connect

#4471 MMU: Set PAUSED_FOR_USER state on MMU error screen
  Firmware/mmu2_reporting.cpp
Labels: Prusa-Link_Connect
