Repository prusa3d/Prusa-Firmware, pull requests merged in 2023-11, with the labels that each got.

#4437 PFW-1294: Don't attempt to find SD file when recovering USB print
  Firmware/eeprom.h
  Firmware/power_panic.cpp
  Firmware/ultralcd.cpp
Labels: powerpanic, Prusa-Link_Connect

#4474 Add en- and disable MMU to M709
  Firmware/Marlin_main.cpp
  Firmware/mmu2.cpp
  Firmware/mmu2.h
  Firmware/mmu2_reporting.cpp
  Firmware/ultralcd.cpp
Labels: Prusa-Link_Connect

#4479 PFW-1523 Add the `S` parameter to `M79`
  Firmware/Marlin_main.cpp
  Firmware/host.cpp
  Firmware/host.h
  Firmware/ultralcd.cpp
  Firmware/util.cpp
  Firmware/util.h
Labels: Post release tasks open

#4495 EEPROM: Formatting cleanup
  Firmware/eeprom.h
Labels: Post release tasks open

#4457 PFW-1184:Basic Printer name in EEPROM
  Firmware/Marlin.h
  Firmware/Marlin_main.cpp
  Firmware/eeprom.cpp
  Firmware/eeprom.h
  Firmware/language.h
Labels: Prusa-Link_Connect

#4399 Add M125
  Firmware/Marlin_main.cpp
Labels: Post release tasks open

#4493 PFW-1206: Implement Marlin's print job timer and add M75-M78
  CMakeLists.txt
  Firmware/Marlin.h
  Firmware/Marlin_main.cpp
  Firmware/Prusa_farm.cpp
  Firmware/cardreader.cpp
  Firmware/cmdqueue.cpp
  Firmware/fancheck.cpp
  Firmware/stopwatch.cpp
  Firmware/stopwatch.h
  Firmware/ultralcd.cpp
  Firmware/ultralcd.h
Labels: Prusa-Link_Connect

#4429 PFW-1525 Add `Set Ready`menu
  CMakeLists.txt
  Firmware/Marlin.h
  Firmware/Marlin_main.cpp
  Firmware/cardreader.cpp
  Firmware/cmdqueue.cpp
  Firmware/messages.cpp
  Firmware/messages.h
  Firmware/printer_state.cpp
  Firmware/printer_state.h
  Firmware/stopwatch.cpp
  Firmware/stopwatch.h
  Firmware/ultralcd.cpp
  Firmware/util.h
  lang/po/Firmware.pot
  lang/po/Firmware_cs.po
  lang/po/Firmware_de.po
  lang/po/Firmware_es.po
  lang/po/Firmware_fr.po
  lang/po/Firmware_hr.po
  lang/po/Firmware_hu.po
  lang/po/Firmware_it.po
  lang/po/Firmware_nl.po
  lang/po/Firmware_no.po
  lang/po/Firmware_pl.po
  lang/po/Firmware_ro.po
  lang/po/Firmware_sk.po
  lang/po/Firmware_sv.po
Labels: Post release tasks open, Prusa-Link_Connect

#4419 M600: reduce stack usage
  Firmware/Marlin.h
  Firmware/Marlin_main.cpp
Labels: powerpanic
